-- Generated by nwg-displays on 2026-09-22 at 16:56:57. Do not edit manually.

hl.monitor({
    output = "desc:Chimei Innolux Corporation 0x1560",
    mode = "1920x1080@144.0",
    position = "0x0",
    scale = 1.0,
    vrr = 0
})
