-- Generated by nwg-displays on 2026-09-20 at 09:43:04. Do not edit manually.

hl.workspace_rule({
    workspace = "6",
    monitor = "desc:Ancor Communications Inc VW222 79LMQS026756",
    default = true
})
hl.workspace_rule({
    workspace = "7",
    monitor = "desc:Ancor Communications Inc VW222 79LMQS026756"
})
hl.workspace_rule({
    workspace = "9",
    monitor = "desc:LG Electronics LG SIGNAGE 0x01010101",
    default = true
})
hl.workspace_rule({
    workspace = "1",
    monitor = "desc:Chimei Innolux Corporation 0x1560",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "desc:Chimei Innolux Corporation 0x1560"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "desc:Chimei Innolux Corporation 0x1560"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "desc:Chimei Innolux Corporation 0x1560"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "desc:Chimei Innolux Corporation 0x1560"
})
