# vim:fileencoding=utf-8:foldmethod=marker

general {
    #{{{
    gaps_in = 5
    gaps_out = 10
    border_size = 1
    resize_on_border = true
    no_focus_fallback = true
    allow_tearing = false
    #}}}
    # snap {{{
    snap {
        enabled = true
        window_gap = 5
        monitor_gap = 10
        respect_gaps = true
    }
    #}}}
}

decoration {
  rounding = 20
  rounding_power = 2

  shadow {
    enabled = true
    range = 4
    render_power = 3
    color = rgba(1a1a1aee)
  }

  blur {
    enabled = true
    size = 3
    passes = 2
    xray = true
    vibrancy = 0.1696
  }
}

misc {
    vfr = true
    vrr = 0

    enable_swallow = false
    swallow_regex = (foot|kitty|allacritty|Alacritty)
    
    animate_manual_resizes = false
    animate_mouse_windowdragging = false

    disable_hyprland_logo = true
    force_default_wallpaper = 0

    on_focus_under_fullscreen = 2
    allow_session_lock_restore = true
    middle_click_paste = false
    focus_on_activate = true
    session_lock_xray = true

    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}
