# ######## Window rules ########

# Disable blur for xwayland context menus
windowrule = match:class ^()$, match:title ^()$, no_blur on

# Disable blur for every window
windowrule = match:class .*, no_blur on

# Floating
windowrule = match:title ^(Open File)(.*)$, center on
windowrule = match:title ^(Open File)(.*)$, float on
windowrule = match:title ^(Select a File)(.*)$, center on
windowrule = match:title ^(Select a File)(.*)$, float on
windowrule = match:title ^(Open Folder)(.*)$, center on
windowrule = match:title ^(Open Folder)(.*)$, float on
windowrule = match:title ^(Save As)(.*)$, center on
windowrule = match:title ^(Save As)(.*)$, float on
windowrule = match:title ^(Library)(.*)$, center on
windowrule = match:title ^(Library)(.*)$, float on
windowrule = match:title ^(File Upload)(.*)$, center on
windowrule = match:title ^(File Upload)(.*)$, float on
windowrule = match:title ^(.*)(wants to save)$, center on
windowrule = match:title ^(.*)(wants to save)$, float on
windowrule = match:title ^(.*)(wants to open)$, center on
windowrule = match:title ^(.*)(wants to open)$, float on
windowrule = match:class ^(blueberry\.py)$, float on
windowrule = match:class ^(pavucontrol)$, float on
windowrule = match:class ^(pavucontrol)$, size (monitor_w*.45) (monitor_h*.45)
windowrule = match:class ^(pavucontrol)$, center on
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float on
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, size (monitor_w*.45) (monitor_h*.45)
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, center on
windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:class ^(nm-connection-editor)$, size (monitor_w*.45) (monitor_h*.45)
windowrule = match:class ^(nm-connection-editor)$, center on
windowrule = match:class .*plasmawindowed.*, float on
windowrule = match:class kcm_.*, float on
windowrule = match:class org.freedesktop.impl.portal.desktop.gtk, float on
windowrule = match:class org.freedesktop.impl.portal.desktop.gtk, size (monitor_w*.60) (monitor_h*.65)
windowrule = match:class steam, float on
windowrule = match:title Steam, tile on
windowrule = match:title Unlock Database - KeePassXC, float on


# --- Tearing ---
#windowrule = match:title .*\.exe, immediate on
#windowrule = match:title .*minecraft.*, immediate on
#windowrule = match:title osu!, immediate on
#windowrule = match:class ^(steam_app).*, immediate on


layerrule {
  name = noctalia
  match:namespace = noctalia-background-.*$
  ignore_alpha = 0.5
  blur = true
  blur_popups = true
}

layerrule {
  name = screenshot-plugin
  match:namespace = noctalia-shell:regionSelector
  no_anim = true
}
